apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "boots.fullname" . }}-role
rules:
- apiGroups:
  - tinkerbell.org
  resources:
  - hardware
  - hardware/status
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - tinkerbell.org
  resources:
  - workflows
  - workflows/status
  verbs:
  - get
  - list
  - watch