apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "boots.fullname" . }}-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "boots.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "boots.fullname" . }}
  namespace: {{ .Release.Namespace }}