# permissions for end users to view inventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inventory-viewer-role
rules:
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - inventories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - inventories/status
  verbs:
  - get
