---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - inventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - inventories/finalizers
  verbs:
  - update
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - inventories/status
  verbs:
  - get
  - patch
  - update
