apiVersion: v1
kind: Service
metadata:
  name: {{ include "rufio.fullname" . }}
  labels:
    {{- include "rufio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rufio.selectorLabels" . | nindent 4 }}
